//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DohrniiFoundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DFResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DFResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DohrniiFoundation.Resources.DFResources", typeof(DFResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dohrnii Academy is the place you go to learn about crypto and investing.
        ///
        ///Our content is created and curated by university professors and lecturers to ensure only the highest quality information is included in our lessons..
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token Expiry Time.
        /// </summary>
        internal static string AccessTokenExpiryText {
            get {
                return ResourceManager.GetString("AccessTokenExpiryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token.
        /// </summary>
        internal static string AccessTokenText {
            get {
                return ResourceManager.GetString("AccessTokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountText {
            get {
                return ResourceManager.GetString("AccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertText {
            get {
                return ResourceManager.GetString("AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Lessons Completed.
        /// </summary>
        internal static string AllLessonsCompletedText {
            get {
                return ResourceManager.GetString("AllLessonsCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory..
        /// </summary>
        internal static string AllMandatoryText {
            get {
                return ResourceManager.GetString("AllMandatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string AlreadyHaveAccountText {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazing!.
        /// </summary>
        internal static string AmazingText {
            get {
                return ResourceManager.GetString("AmazingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string AsteriskText {
            get {
                return ResourceManager.GetString("AsteriskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome!.
        /// </summary>
        internal static string AwesomeText {
            get {
                return ResourceManager.GetString("AwesomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric Details.
        /// </summary>
        internal static string BiometricDetailsText {
            get {
                return ResourceManager.GetString("BiometricDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is our app about?.
        /// </summary>
        internal static string BoardingHeader1 {
            get {
                return ResourceManager.GetString("BoardingHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some basic terms.
        /// </summary>
        internal static string BoardingHeader2 {
            get {
                return ResourceManager.GetString("BoardingHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About quizzes.
        /// </summary>
        internal static string BoardingHeader3 {
            get {
                return ResourceManager.GetString("BoardingHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our tokens.
        /// </summary>
        internal static string BoardingHeader4 {
            get {
                return ResourceManager.GetString("BoardingHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crypto lessons app − earn and get tokens for free.
        /// </summary>
        internal static string BoardingTitle1 {
            get {
                return ResourceManager.GetString("BoardingTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string CameraText {
            get {
                return ResourceManager.GetString("CameraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        internal static string ChallengesText {
            get {
                return ResourceManager.GetString("ChallengesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change First Name.
        /// </summary>
        internal static string ChangeFirstNameText {
            get {
                return ResourceManager.GetString("ChangeFirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Last Name.
        /// </summary>
        internal static string ChangeLastNameText {
            get {
                return ResourceManager.GetString("ChangeLastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Name.
        /// </summary>
        internal static string ChangeUserNameText {
            get {
                return ResourceManager.GetString("ChangeUserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chapter progress.
        /// </summary>
        internal static string ChapterProgressText {
            get {
                return ResourceManager.GetString("ChapterProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        internal static string ChaptersText {
            get {
                return ResourceManager.GetString("ChaptersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string ChapterText {
            get {
                return ResourceManager.GetString("ChapterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you are connected to the internet.
        /// </summary>
        internal static string CheckInternetText {
            get {
                return ResourceManager.GetString("CheckInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string CheckText {
            get {
                return ResourceManager.GetString("CheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Complete!.
        /// </summary>
        internal static string ClassCompleteText {
            get {
                return ResourceManager.GetString("ClassCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClassText {
            get {
                return ResourceManager.GetString("ClassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        internal static string ClickHereText {
            get {
                return ResourceManager.GetString("ClickHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click button below to unlock this chapter quiz with {0} crypto jelly.
        /// </summary>
        internal static string ClickHereToUlockChapteQuizText {
            get {
                return ResourceManager.GetString("ClickHereToUlockChapteQuizText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect more XP to Convert.
        /// </summary>
        internal static string CollectmoreXPtoConvertText {
            get {
                return ResourceManager.GetString("CollectmoreXPtoConvertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string ConfirmNewPasswordText {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Wallet.
        /// </summary>
        internal static string ConnectWalletText {
            get {
                return ResourceManager.GetString("ConnectWalletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string ContactNumberText {
            get {
                return ResourceManager.GetString("ContactNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue lesson.
        /// </summary>
        internal static string ContinueLessonText {
            get {
                return ResourceManager.GetString("ContinueLessonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert into Jellyfish.
        /// </summary>
        internal static string ConvertIntoJellyfishText {
            get {
                return ResourceManager.GetString("ConvertIntoJellyfishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert XP.
        /// </summary>
        internal static string ConvertXPText {
            get {
                return ResourceManager.GetString("ConvertXPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct answer is:.
        /// </summary>
        internal static string CorrectAnswerText {
            get {
                return ResourceManager.GetString("CorrectAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct!.
        /// </summary>
        internal static string CorrectText {
            get {
                return ResourceManager.GetString("CorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string CourseText {
            get {
                return ResourceManager.GetString("CourseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when you have 750 XP you get one jellyfish, it gives you the right to participate in the quiz and get tokens for correct answers.
        /// </summary>
        internal static string CryptoJellyContentText {
            get {
                return ResourceManager.GetString("CryptoJellyContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Jelly.
        /// </summary>
        internal static string CryptoJellyText {
            get {
                return ResourceManager.GetString("CryptoJellyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Support.
        /// </summary>
        internal static string CustomerSupportText {
            get {
                return ResourceManager.GetString("CustomerSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionTitleText {
            get {
                return ResourceManager.GetString("DescriptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHN - When you have at least one jellyfish you have the right to take part in the quiz. By giving the correct answers to all questions, you will receive 10 DHN tokens, which definitely motivates you to study cool 😉.
        /// </summary>
        internal static string DHNBody {
            get {
                return ResourceManager.GetString("DHNBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you have at least one jellyfish you have the right to take part in the quiz. By giving the correct answers to all questions, you will receive 10 DHN tokens, which definitely motivates you to study cool.
        /// </summary>
        internal static string DHNContentText {
            get {
                return ResourceManager.GetString("DHNContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHN is an empowerment token and its objective is to reward the community as they go through the curriculum..
        /// </summary>
        internal static string DHNisanempowermentText {
            get {
                return ResourceManager.GetString("DHNisanempowermentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $DHN is the native token of the Dohrnii platform..
        /// </summary>
        internal static string DHNisthenativetokenText {
            get {
                return ResourceManager.GetString("DHNisthenativetokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHN.
        /// </summary>
        internal static string DHNText {
            get {
                return ResourceManager.GetString("DHNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOHRNII DONATES.
        /// </summary>
        internal static string DohrniidonatesText {
            get {
                return ResourceManager.GetString("DohrniidonatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string DontHaveAccountText {
            get {
                return ResourceManager.GetString("DontHaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your message and one of our support team will get back to you.
        /// </summary>
        internal static string DropCustomerSupportText {
            get {
                return ResourceManager.GetString("DropCustomerSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each class has 10 questions, for each correct answer you are given 5 XP..
        /// </summary>
        internal static string EachclasshasText {
            get {
                return ResourceManager.GetString("EachclasshasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 204 earned.
        /// </summary>
        internal static string EarnedText {
            get {
                return ResourceManager.GetString("EarnedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string EditProfileText {
            get {
                return ResourceManager.GetString("EditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddressText {
            get {
                return ResourceManager.GetString("EmailAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address associated with your account..
        /// </summary>
        internal static string EnterEmailText {
            get {
                return ResourceManager.GetString("EnterEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Jellyfish(s).
        /// </summary>
        internal static string EnterJellyfishText {
            get {
                return ResourceManager.GetString("EnterJellyfishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password first.
        /// </summary>
        internal static string EnterNewPasswordFirstText {
            get {
                return ResourceManager.GetString("EnterNewPasswordFirstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password first.
        /// </summary>
        internal static string EnterPasswordFirstText {
            get {
                return ResourceManager.GetString("EnterPasswordFirstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! No internet connection.
        /// </summary>
        internal static string ErrorMessageText {
            get {
                return ResourceManager.GetString("ErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent!.
        /// </summary>
        internal static string ExcellentText {
            get {
                return ResourceManager.GetString("ExcellentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Investment Concepts.
        /// </summary>
        internal static string ExploreInvestmentText {
            get {
                return ResourceManager.GetString("ExploreInvestmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string FacebookText {
            get {
                return ResourceManager.GetString("FacebookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQText {
            get {
                return ResourceManager.GetString("FAQText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the details given below.
        /// </summary>
        internal static string FillDetailsGivenBelow {
            get {
                return ResourceManager.GetString("FillDetailsGivenBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishText {
            get {
                return ResourceManager.GetString("FinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPasswordText2 {
            get {
                return ResourceManager.GetString("ForgotPasswordText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotyourpasswordText {
            get {
                return ResourceManager.GetString("ForgotyourpasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        internal static string FriendRequestText {
            get {
                return ResourceManager.GetString("FriendRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string GalleryText {
            get {
                return ResourceManager.GetString("GalleryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string GenericErrorMessageText {
            get {
                return ResourceManager.GetString("GenericErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Ready for a Whole Lot of Knowledge!.
        /// </summary>
        internal static string GetReadyText {
            get {
                return ResourceManager.GetString("GetReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Dashboard.
        /// </summary>
        internal static string GoDashboardText {
            get {
                return ResourceManager.GetString("GoDashboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good job!.
        /// </summary>
        internal static string GoodJobText {
            get {
                return ResourceManager.GetString("GoodJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great job!.
        /// </summary>
        internal static string GreatJobText {
            get {
                return ResourceManager.GetString("GreatJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this lessons:.
        /// </summary>
        internal static string InthislessonsText {
            get {
                return ResourceManager.GetString("InthislessonsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Jelly amount!.
        /// </summary>
        internal static string InvalidJellyAmountText {
            get {
                return ResourceManager.GetString("InvalidJellyAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor&apos;s Profile.
        /// </summary>
        internal static string InvestorText {
            get {
                return ResourceManager.GetString("InvestorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest.
        /// </summary>
        internal static string InvestText {
            get {
                return ResourceManager.GetString("InvestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a friend.
        /// </summary>
        internal static string InviteFriendText {
            get {
                return ResourceManager.GetString("InviteFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfish.
        /// </summary>
        internal static string JelleyfishText {
            get {
                return ResourceManager.GetString("JelleyfishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelly Amount.
        /// </summary>
        internal static string JellyAmountText {
            get {
                return ResourceManager.GetString("JellyAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when you have 750 HP you get one jellyfish, it gives you the right to participate in the quiz and get tokens for correct answers.
        /// </summary>
        internal static string JellyBody {
            get {
                return ResourceManager.GetString("JellyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfish(s).
        /// </summary>
        internal static string JellyfishesText {
            get {
                return ResourceManager.GetString("JellyfishesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelly.
        /// </summary>
        internal static string JellyText {
            get {
                return ResourceManager.GetString("JellyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Our Community.
        /// </summary>
        internal static string JoinCommunityText {
            get {
                return ResourceManager.GetString("JoinCommunityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep it up!.
        /// </summary>
        internal static string KeepItUpText {
            get {
                return ResourceManager.GetString("KeepItUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN ABOUT CRYPTO &amp; EARN TOKENS.
        /// </summary>
        internal static string LearnAboutCryptoText {
            get {
                return ResourceManager.GetString("LearnAboutCryptoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string LearnText {
            get {
                return ResourceManager.GetString("LearnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lesson is locked.
        /// </summary>
        internal static string LessonLockedAlertText {
            get {
                return ResourceManager.GetString("LessonLockedAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open this one, complete all the lessons above..
        /// </summary>
        internal static string LessonLockedMsgText {
            get {
                return ResourceManager.GetString("LessonLockedMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Progress.
        /// </summary>
        internal static string LessonProgressText {
            get {
                return ResourceManager.GetString("LessonProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        internal static string LessonsText {
            get {
                return ResourceManager.GetString("LessonsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string LockedText {
            get {
                return ResourceManager.GetString("LockedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string LogoutAlertText {
            get {
                return ResourceManager.GetString("LogoutAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Concept Detail-Image.
        /// </summary>
        internal static string LongTermConceptDetailImageText {
            get {
                return ResourceManager.GetString("LongTermConceptDetailImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Concept Detail-Text.
        /// </summary>
        internal static string LongTermConceptDetailText {
            get {
                return ResourceManager.GetString("LongTermConceptDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Concept Detail-Video.
        /// </summary>
        internal static string LongTermConceptDetailVideoText {
            get {
                return ResourceManager.GetString("LongTermConceptDetailVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-Term Concepts.
        /// </summary>
        internal static string LongTermConceptsText {
            get {
                return ResourceManager.GetString("LongTermConceptsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loreum Ipsum text area is here for the answer..
        /// </summary>
        internal static string LoremIpsumAnswerText {
            get {
                return ResourceManager.GetString("LoremIpsumAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum is a there is used to demonstrate the not visual form?.
        /// </summary>
        internal static string LoremIpsumFormText {
            get {
                return ResourceManager.GetString("LoremIpsumFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing and graphic design, Lorem ipsum is a there placeholder text commonly used to demonstrate the ?.
        /// </summary>
        internal static string LoremIpsumQuestionText {
            get {
                return ResourceManager.GetString("LoremIpsumQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum is a there placeholder text commonly used to demonstrate the not visual form?.
        /// </summary>
        internal static string LoreumIpsumDescrpText {
            get {
                return ResourceManager.GetString("LoreumIpsumDescrpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loreum Ipsum.
        /// </summary>
        internal static string LoreumIpsumText {
            get {
                return ResourceManager.GetString("LoreumIpsumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loreum Ipsum Text Area.
        /// </summary>
        internal static string LoreumIpsumTextAreaText {
            get {
                return ResourceManager.GetString("LoreumIpsumTextAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string ModulesText {
            get {
                return ResourceManager.GetString("ModulesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string MoreText {
            get {
                return ResourceManager.GetString("MoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature and scope of economics.
        /// </summary>
        internal static string NatureScopeText {
            get {
                return ResourceManager.GetString("NatureScopeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password must be same..
        /// </summary>
        internal static string NewAndConfirmPasswordSameText {
            get {
                return ResourceManager.GetString("NewAndConfirmPasswordSameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPasswordText {
            get {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice job!.
        /// </summary>
        internal static string NiceJobText {
            get {
                return ResourceManager.GetString("NiceJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicely done!.
        /// </summary>
        internal static string NicelyDoneText {
            get {
                return ResourceManager.GetString("NicelyDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice!.
        /// </summary>
        internal static string NiceText {
            get {
                return ResourceManager.GetString("NiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No class available here, please check back later..
        /// </summary>
        internal static string NoAvailableClassText {
            get {
                return ResourceManager.GetString("NoAvailableClassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Camera.
        /// </summary>
        internal static string NoCameraText {
            get {
                return ResourceManager.GetString("NoCameraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Concepts Found..
        /// </summary>
        internal static string NoConceptsFoundText {
            get {
                return ResourceManager.GetString("NoConceptsFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        internal static string NoInternetConnectionText {
            get {
                return ResourceManager.GetString("NoInternetConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enought XP to convert to {0} Crypto Jelly.
        /// </summary>
        internal static string NotEnoughXPText {
            get {
                return ResourceManager.GetString("NotEnoughXPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string NoticeText {
            get {
                return ResourceManager.GetString("NoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Video Found..
        /// </summary>
        internal static string NoVideoFoundText {
            get {
                return ResourceManager.GetString("NoVideoFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string OldPasswordText {
            get {
                return ResourceManager.GetString("OldPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string OopsText {
            get {
                return ResourceManager.GetString("OopsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or sign up with.
        /// </summary>
        internal static string OrSignUpWithText {
            get {
                return ResourceManager.GetString("OrSignUpWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our content is created and curated by university professors and lecturers to ensure only the highest quality information is included in our lessons..
        /// </summary>
        internal static string OurcontentText {
            get {
                return ResourceManager.GetString("OurcontentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our tokens.
        /// </summary>
        internal static string OurtokensText {
            get {
                return ResourceManager.GetString("OurtokensText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string PassedText {
            get {
                return ResourceManager.GetString("PassedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password must be same..
        /// </summary>
        internal static string PasswordAndConfirmPasswordSameText {
            get {
                return ResourceManager.GetString("PasswordAndConfirmPasswordSameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Not Supported.
        /// </summary>
        internal static string PhotosNotSupportedText {
            get {
                return ResourceManager.GetString("PhotosNotSupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your investor profile..
        /// </summary>
        internal static string Pleasecompleteinvestor {
            get {
                return ResourceManager.GetString("Pleasecompleteinvestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only characters in first and last name..
        /// </summary>
        internal static string PleaseEnterCharactersText {
            get {
                return ResourceManager.GetString("PleaseEnterCharactersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the confirm password..
        /// </summary>
        internal static string PleaseEnterConfirmPasswordText {
            get {
                return ResourceManager.GetString("PleaseEnterConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address..
        /// </summary>
        internal static string PleaseEnterEmail {
            get {
                return ResourceManager.GetString("PleaseEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address and password..
        /// </summary>
        internal static string PleaseEnterEmailAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterEmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter message..
        /// </summary>
        internal static string PleaseentermessageText {
            get {
                return ResourceManager.GetString("PleaseentermessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password..
        /// </summary>
        internal static string PleaseEnterNewPasswordText {
            get {
                return ResourceManager.GetString("PleaseEnterNewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password..
        /// </summary>
        internal static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the user name..
        /// </summary>
        internal static string PleaseEnterUserNameText {
            get {
                return ResourceManager.GetString("PleaseEnterUserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid contact number..
        /// </summary>
        internal static string PleaseEnterValidContactText {
            get {
                return ResourceManager.GetString("PleaseEnterValidContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address..
        /// </summary>
        internal static string PleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("PleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address and password..
        /// </summary>
        internal static string PleaseEnterValidEmailAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterValidEmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid password..
        /// </summary>
        internal static string PleaseEnterValidPassword {
            get {
                return ResourceManager.GetString("PleaseEnterValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to your account.
        /// </summary>
        internal static string PleaseLoginText {
            get {
                return ResourceManager.GetString("PleaseLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retake the questionnaire..
        /// </summary>
        internal static string PleaseretakequestionnaireText {
            get {
                return ResourceManager.GetString("PleaseretakequestionnaireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email address by clicking the button below..
        /// </summary>
        internal static string PleaseVerifyEmailText {
            get {
                return ResourceManager.GetString("PleaseVerifyEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousText {
            get {
                return ResourceManager.GetString("PreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam congue viverra hac morbi vitae. Ipsum ornare vestibulum consequat ac massa in ornare tincidunt. Et, risus non dictumst erat mauris porta mi ultricies. Tempor tortor donec sed purus. Pellentesque scelerisque aliquam nisi id adipiscing amet quisque. Egestas facilisi eget sit sollicitudin et nisl. 
        ///
        ///Dignissim leo sed gravida risus, elit pellentesque sed quisque. Aenean aliquam ipsum, ut morbi. Montes, viverra ut sed magna amet.
        ///
        ///Lorem ipsum dolor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyPolicyContent {
            get {
                return ResourceManager.GetString("PrivacyPolicyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileText {
            get {
                return ResourceManager.GetString("ProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string ProgressText {
            get {
                return ResourceManager.GetString("ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        internal static string QuestionnaireText {
            get {
                return ResourceManager.GetString("QuestionnaireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire updated successfully..
        /// </summary>
        internal static string QuestionnaireUpdatedSuccessfullyText {
            get {
                return ResourceManager.GetString("QuestionnaireUpdatedSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string QuestionsText {
            get {
                return ResourceManager.GetString("QuestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already taken this chapter quiz.
        /// </summary>
        internal static string QuizAlreadyTakenText {
            get {
                return ResourceManager.GetString("QuizAlreadyTakenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Results.
        /// </summary>
        internal static string QuizResultText {
            get {
                return ResourceManager.GetString("QuizResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string QuizText {
            get {
                return ResourceManager.GetString("QuizText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizz.
        /// </summary>
        internal static string QuizzText {
            get {
                return ResourceManager.GetString("QuizzText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Xp Per Class.
        /// </summary>
        internal static string ReceivedXpPerClassText {
            get {
                return ResourceManager.GetString("ReceivedXpPerClassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received xp per lesson.
        /// </summary>
        internal static string ReceivedXpPerPersonText {
            get {
                return ResourceManager.GetString("ReceivedXpPerPersonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem your dhn.
        /// </summary>
        internal static string RedeemyourdhnText {
            get {
                return ResourceManager.GetString("RedeemyourdhnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to use the app.
        /// </summary>
        internal static string RegisterToUseAppText {
            get {
                return ResourceManager.GetString("RegisterToUseAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationText {
            get {
                return ResourceManager.GetString("RegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RemembermeText {
            get {
                return ResourceManager.GetString("RemembermeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit your email that you use in signing up for to receive the reset password link.
        /// </summary>
        internal static string ResetPasswordLinkText {
            get {
                return ResourceManager.GetString("ResetPasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordText {
            get {
                return ResourceManager.GetString("ResetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password?.
        /// </summary>
        internal static string ResetyourpasswordText {
            get {
                return ResourceManager.GetString("ResetyourpasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        internal static string RewardText {
            get {
                return ResourceManager.GetString("RewardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scare Resources.
        /// </summary>
        internal static string ScareResourcesText {
            get {
                return ResourceManager.GetString("ScareResourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option.
        /// </summary>
        internal static string SelectOptionText {
            get {
                return ResourceManager.GetString("SelectOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share invite with friends.
        /// </summary>
        internal static string ShareWithFriendText {
            get {
                return ResourceManager.GetString("ShareWithFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        internal static string ShowPasswordText {
            get {
                return ResourceManager.GetString("ShowPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInText {
            get {
                return ResourceManager.GetString("SignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Use App.
        /// </summary>
        internal static string SignInToUseAppText {
            get {
                return ResourceManager.GetString("SignInToUseAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your mail to get the 5 digits code to verify you sign in.
        /// </summary>
        internal static string SignUpNoticeText {
            get {
                return ResourceManager.GetString("SignUpNoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTICE.
        /// </summary>
        internal static string SignUpNoticeTitleText {
            get {
                return ResourceManager.GetString("SignUpNoticeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid password.\nPassword should contain atleast one upper case, one lower case, one special character and one numeric.\nPassword contains minimum 8 and maximum 16 characters..
        /// </summary>
        internal static string SignupPasswordValidationText {
            get {
                return ResourceManager.GetString("SignupPasswordValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to get started!.
        /// </summary>
        internal static string SignUpStartText {
            get {
                return ResourceManager.GetString("SignUpStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string SignupSText {
            get {
                return ResourceManager.GetString("SignupSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to get started!.
        /// </summary>
        internal static string SignupToStartText {
            get {
                return ResourceManager.GetString("SignupToStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup with email.
        /// </summary>
        internal static string SignUpWithText {
            get {
                return ResourceManager.GetString("SignUpWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Sign In With.
        /// </summary>
        internal static string SignWithText {
            get {
                return ResourceManager.GetString("SignWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string SkipText {
            get {
                return ResourceManager.GetString("SkipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string SocialText {
            get {
                return ResourceManager.GetString("SocialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some basic terms.
        /// </summary>
        internal static string SomebasictermsText {
            get {
                return ResourceManager.GetString("SomebasictermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string SomethingWrongText {
            get {
                return ResourceManager.GetString("SomethingWrongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! No camera available..
        /// </summary>
        internal static string SorryNocameraavailableText {
            get {
                return ResourceManager.GetString("SorryNocameraavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Permission not granted to photos..
        /// </summary>
        internal static string SorryPermissionnotgrantedtophotosText {
            get {
                return ResourceManager.GetString("SorryPermissionnotgrantedtophotosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Lesson.
        /// </summary>
        internal static string StartLessonText {
            get {
                return ResourceManager.GetString("StartLessonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Questions.
        /// </summary>
        internal static string StartQuestionsText {
            get {
                return ResourceManager.GetString("StartQuestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only take this quiz once. Make sure you are ready to take this before you click on start button..
        /// </summary>
        internal static string StartQuizInfoText {
            get {
                return ResourceManager.GetString("StartQuizInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Quiz.
        /// </summary>
        internal static string StartQuizText {
            get {
                return ResourceManager.GetString("StartQuizText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategies.
        /// </summary>
        internal static string StrategiesText {
            get {
                return ResourceManager.GetString("StrategiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully verified your account..
        /// </summary>
        internal static string SuccessfullyVerifiedText {
            get {
                return ResourceManager.GetString("SuccessfullyVerifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed, click button below to login.
        /// </summary>
        internal static string SuccessfulRegistrationText {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string SuccessfulText {
            get {
                return ResourceManager.GetString("SuccessfulText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryText {
            get {
                return ResourceManager.GetString("SummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsAndConditionsText {
            get {
                return ResourceManager.GetString("TermsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Area is Here.
        /// </summary>
        internal static string TextAreaHereText {
            get {
                return ResourceManager.GetString("TextAreaHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is Here.
        /// </summary>
        internal static string TextHereText {
            get {
                return ResourceManager.GetString("TextHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dohrnii Academy is the place you go to learn about crypto and investing..
        /// </summary>
        internal static string TheDohrniiAcademyText {
            get {
                return ResourceManager.GetString("TheDohrniiAcademyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of chapter quiz is your chance to win DHN tokens..
        /// </summary>
        internal static string TheendText {
            get {
                return ResourceManager.GetString("TheendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to they are used to unlock the quiz at the end of each chapter..
        /// </summary>
        internal static string theyareusedText {
            get {
                return ResourceManager.GetString("theyareusedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token received.
        /// </summary>
        internal static string TokenreceivedText {
            get {
                return ResourceManager.GetString("TokenreceivedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to lessons.
        /// </summary>
        internal static string tolessonsText {
            get {
                return ResourceManager.GetString("tolessonsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgainText {
            get {
                return ResourceManager.GetString("TryAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        internal static string UnlockedText {
            get {
                return ResourceManager.GetString("UnlockedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now start quiz by clicking on start button.
        /// </summary>
        internal static string UnlockQuizSubtitle {
            get {
                return ResourceManager.GetString("UnlockQuizSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string UnlockText {
            get {
                return ResourceManager.GetString("UnlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name cannot be start with number..
        /// </summary>
        internal static string UserWithOutNumberText {
            get {
                return ResourceManager.GetString("UserWithOutNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        internal static string VerificationCodePlaceholder {
            get {
                return ResourceManager.GetString("VerificationCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified!.
        /// </summary>
        internal static string VerifiedText {
            get {
                return ResourceManager.GetString("VerifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email address.
        /// </summary>
        internal static string VerifyEmailText {
            get {
                return ResourceManager.GetString("VerifyEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email.
        /// </summary>
        internal static string VerifyYourEmailText {
            get {
                return ResourceManager.GetString("VerifyYourEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAllText {
            get {
                return ResourceManager.GetString("ViewAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit your email that you use in signing up for to receive the reset password link.
        /// </summary>
        internal static string VisityouremailText {
            get {
                return ResourceManager.GetString("VisityouremailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Address.
        /// </summary>
        internal static string WalletAddressText {
            get {
                return ResourceManager.GetString("WalletAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanna unlock the quizzes.
        /// </summary>
        internal static string WannaunlockText {
            get {
                return ResourceManager.GetString("WannaunlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a multichain token available on  Ethereum, Binance smart chain, VeChain and Mattic polygon networks..
        /// </summary>
        internal static string WeareamultichainText {
            get {
                return ResourceManager.GetString("WeareamultichainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are turning Education UpSideDown with our Learn to Earn Feature.
        /// </summary>
        internal static string WeareturningText {
            get {
                return ResourceManager.GetString("WeareturningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Dhornii.
        /// </summary>
        internal static string WelcomeDhorniiText {
            get {
                return ResourceManager.GetString("WelcomeDhorniiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Dohnrii.
        /// </summary>
        internal static string WelcomeToDohnriiText {
            get {
                return ResourceManager.GetString("WelcomeToDohnriiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Crypto Jelly?.
        /// </summary>
        internal static string WhatisCryptoJellyText {
            get {
                return ResourceManager.GetString("WhatisCryptoJellyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is DHN?.
        /// </summary>
        internal static string WhatisDHNText {
            get {
                return ResourceManager.GetString("WhatisDHNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Dohrnii about?.
        /// </summary>
        internal static string WhatisDohrniiaboutText {
            get {
                return ResourceManager.GetString("WhatisDohrniiaboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is XP?.
        /// </summary>
        internal static string WhatisXPText {
            get {
                return ResourceManager.GetString("WhatisXPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get XP as a reward for completing a class / lesson. There are 10 questions in the class, for each question you are given 50 XP, for the passed class you will receive exactly 500 XP.
        /// </summary>
        internal static string XPBody {
            get {
                return ResourceManager.GetString("XPBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP Collected.
        /// </summary>
        internal static string XPCollectedText {
            get {
                return ResourceManager.GetString("XPCollectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get XP as a reward for completing a class / lesson. There are 10 questions in the class,.
        /// </summary>
        internal static string XPContentText {
            get {
                return ResourceManager.GetString("XPContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for each question you are given 50 XP, for the passed class you will receive exactly 500 XP.
        /// </summary>
        internal static string XPContentTextNext {
            get {
                return ResourceManager.GetString("XPContentTextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP Remaining.
        /// </summary>
        internal static string XPRemainingText {
            get {
                return ResourceManager.GetString("XPRemainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP Rewarded.
        /// </summary>
        internal static string XPRewardedText {
            get {
                return ResourceManager.GetString("XPRewardedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        internal static string XPText {
            get {
                return ResourceManager.GetString("XPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP will be spend.
        /// </summary>
        internal static string XPWillBeSentText {
            get {
                return ResourceManager.GetString("XPWillBeSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also exchange them for some Crypto Jellyz!.
        /// </summary>
        internal static string YoucanalsoexchangeText {
            get {
                return ResourceManager.GetString("YoucanalsoexchangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can exchange 1 Crypto Jelly for 750 HP.
        /// </summary>
        internal static string YoucanexchangeText {
            get {
                return ResourceManager.GetString("YoucanexchangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re cool! Keep it up.
        /// </summary>
        internal static string YoucoolKeepitupText {
            get {
                return ResourceManager.GetString("YoucoolKeepitupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get XP as a reward for each correct answer to a class..
        /// </summary>
        internal static string YougetXPText {
            get {
                return ResourceManager.GetString("YougetXPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message here.
        /// </summary>
        internal static string YourMessageHereText {
            get {
                return ResourceManager.GetString("YourMessageHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password must be different from the previous password..
        /// </summary>
        internal static string YourNewPasswordText {
            get {
                return ResourceManager.GetString("YourNewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Progress.
        /// </summary>
        internal static string YourProgressText {
            get {
                return ResourceManager.GetString("YourProgressText", resourceCulture);
            }
        }
    }
}
